### ISSUE TITLE
Null response na verwijderen cookies terwijl ingelogd

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/mijn-nijmegen#253]
```
2022-12-19T09:42:41.453Z 28aa523b-5ff7-4cb5-a649-811cdab012c1 ERROR Error: all handler params are required
at exports.uitkeringsRequestHandler (/var/task/uitkeringsRequestHandler.js:8:59)
at Runtime.exports.handler (/var/task/index.js:29:22)
```

Is te triggeren door in te loggen, alle cookies weg te gooien en dan naar mijn-uitkeringen of mijn-gegevens te gaan. Is een aantal keer op productie gebeurt zo te zien. De response is dan 'null'.

**Comment by joostvanderborg** [comment]
Directe response is beter in https://github.com/GemeenteNijmegen/mijn-uitkering/pull/124. Error ontstaat omdat ook op lege cookiestring gecheckt wordt. Aankomen met lege cookie betekent eigenlijk: geen sessie, dus redirect naar login. Dat moet nog aangepast.
